name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK with PWABuilder
        uses: pwa-builder/pwabuilder-action@v1
        with:
          path: ./
